### ISSUE TITLE
'referensi_copy' made by require

### ISSUE THREAD

**Issue by onurparlar** [mushlih-almubarak/Insert-Link-Reference-In-Copied-Text#18]
Hello,
Maybe this is nothing but I just want to share to understand...

`WordPress database error Server shutdown in progress for query SELECT option_value FROM wp8i_options WHERE option_name = 'referensi_copy' made by require('wp-blog-header.php'), require_once('wp-load.php'), require_once('wp-config.php'), require_once('wp-settings.php'), include_once('/plugins/insert-reference/Reference.php'), require_once('/plugins/insert-reference/Functions.php')`

Thank you

**Comment by mushlih-almubarak** [comment]
Hi, thanks for the report, can you tell me where the error appears? After clicking what?

**Comment by onurparlar** [comment]
I was seeing that in PHP Error Log plugin results...

but I didn't see in last days...

**Comment by mushlih-almubarak** [comment]
Maybe it's just a temporary error, because I also don't see any error on my site.

I will close this issue now because the error is resolved, you can re-open it or create a new issue if something else happens.

Thanks.

**Comment by onurparlar** [comment]
Thank you for your quick response and help...

**Comment by mushlih-almubarak** [comment]
No problem, thank you too for the report
